name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run script
        run: |
          sh <(curl -sSf https://downloads.nordcdn.com/apps/linux/install.sh)
          sudo usermod -aG nordvpn $USER
          sudo nordvpn login --username rescalera@lspt.com --password ${{ secrets.NORDVPNPASSWORD }}
          sudo nordvpn set technology nordlynx
          ./NordVpnToWireguard.sh --city Berlin
          cat NordVPN.conf
