name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run script
        run: |
          sh <(curl -sSf https://downloads.nordcdn.com/apps/linux/install.sh)
          sudo usermod -aG nordvpn $USER
          sudo nordvpn login --username rescalera@lspt.com --password ${{ secrets.NORDVPNPASSWORD }}
          sudo nordvpn set technology nordlynx
          sudo nordvpn c > /dev/null 2>&1

          # Preparing the Interface section
          echo "[Interface]" > Nordvpn.conf
          privateKey=`sudo wg show nordlynx private-key`
          echo "PrivateKey = $privateKey" >> Nordvpn.conf
          echo "ListenPort = 51820" >> Nordvpn.conf
          localAddress=`ifconfig nordlynx | grep inet |  awk -v OFS='\n' '{ print $2 }'`
          echo "Address = $localAddress/32" >> Nordvpn.conf
          echo "DNS = 103.86.96.100, 103.86.99.100" >> Nordvpn.conf
          echo "" >> Nordvpn.conf

          # Gathering info for the Peer section
          curl -s "https://api.nordvpn.com/v1/servers/recommendations?&filters\[servers_technologies\]\[identifier\]=wireguard_udp&limit=1"|jq -r '.[]|.hostname, .station, (.locations|.[]|.country|.city.name), (.locations|.[]|.country|.name), (.technologies|.[].metadata|.[].value), .load' >> Peer.txt

          # Disconnect from NordVPN
          sudo nordvpn d > /dev/null 2>&1

          # Preparing the Peer section 
          endpoint=`grep -m 1 -o '.*' Peer.txt | tail -n 1`
          publicKey=`grep -m 5 -o '.*' Peer.txt | tail -n 1`
          
          rm Peer.txt
          
          echo "[Peer]" >> Nordvpn.conf
          echo "PublicKey = $publicKey" >> Nordvpn.conf
          echo "AllowedIPs = 0.0.0.0/0" >> Nordvpn.conf
          echo "Endpoint = $endpoint:51820" >> Nordvpn.conf
          echo "PersistentKeepalive = 25" >> Nordvpn.conf
          
          # Renaming config file to show the endpoint country id and server number
          outputFileName=`echo $endpoint |  grep -o '^[^.]*'`
          outputFileName=`echo "NordVPN.conf"`
          
          mv Nordvpn.conf $outputFileName
          
          echo "Wireguard configuration file $outputFileName created successfully!"
